# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: iqbalrahmann.github.io
title: BERANDA
email: iqbalrahman@gmail.com
author: Iqbal Rahman
description: > # "Write an awesome description for your new site here. 
  You can edit this line in _config.yml. It will appear in your document 
  head meta (for Google search results) and in your feed.xml site 
  description.
copyright: 'Copyright &copy; 2016 Iqbal Rahman. All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #
social:
  - title: twitter
    url: //www.twitter.com/iqbalrahman
  - title: facebook
    url: //www.facebook.com/iqbal.r.9
  - title: gmail
    url: https://accounts.google.com/ServiceLogin?
    social:
  - title: SIF
    url: http://sif.uin-suska.ac.id/
  - title: UIN
    url: http://uin-suska.ac.id/
    
